<?php

use App\Livewire\LandingPage;
use App\Livewire\List\ShowList;
use App\Livewire\Settings\Appearance;
use App\Livewire\Settings\Password;
use App\Livewire\Settings\Profile; // Generated by Copilot
use App\Livewire\List\CreateList;
use App\Livewire\List\ShowExamples;
use App\Livewire\List\VoteRound;
use App\Livewire\List\RankedResults;
use Illuminate\Support\Facades\Route;

Route::get('/', LandingPage::class)->name('home'); // Generated by Copilot

Route::view('dashboard', 'dashboard')
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::middleware(['auth'])->group(function () {
    Route::redirect('settings', 'settings/profile');

    Route::get('settings/profile', Profile::class)->name('settings.profile');
    Route::get('settings/password', Password::class)->name('settings.password');
    Route::get('settings/appearance', Appearance::class)->name('settings.appearance');
    Route::get('/lists/{list}/results', RankedResults::class)->name('lists.results');
});

Route::get('/timer', function () {
    return view('timer');
});

Route::get('/lists/create', CreateList::class)->name('lists.create');
Route::get('/lists/examples', ShowExamples::class)->name('lists.examples');
Route::get('/lists/{list}/vote', VoteRound::class)->name('lists.vote');
Route::get('/lists/{list}', ShowList::class)->name('lists.show');

require __DIR__.'/auth.php';
