{{-- Generated by Copilot --}}
<div class="min-h-screen flex flex-col justify-center items-center bg-gradient-to-br from-blue-50 via-blue-100 to-teal-100">
    <div class="w-full max-w-2xl mx-auto flex flex-col md:flex-row rounded-3xl shadow-xl overflow-hidden">
        <!-- Left: App Info -->
        <div class="flex-1 bg-blue-600 text-white p-8 flex flex-col justify-center">
            <h1 class="text-4xl font-extrabold mb-4 drop-shadow">Choices</h1>
            <p class="text-lg mb-6 opacity-90">Make better decisions, faster. Let our app guide you through your toughest choices with clarity and confidence.</p>
            <button wire:click="getStarted" class="mt-4 px-8 py-3 bg-white text-blue-700 font-semibold rounded-lg shadow hover:bg-blue-50 hover:scale-105 transition-all text-lg focus:outline-none focus:ring-2 focus:ring-blue-300">
                Get Started
            </button>
        </div>
        <!-- Right: Illustration or Accent -->
        <div class="flex-1 bg-teal-50 flex items-center justify-center p-8">
            <svg width="120" height="120" fill="none" viewBox="0 0 120 120" aria-hidden="true">
                <circle cx="60" cy="60" r="56" fill="#e0f2fe" stroke="#38bdf8" stroke-width="4" />
                <path d="M60 35v50M35 60h50" stroke="#0ea5e9" stroke-width="6" stroke-linecap="round"/>
            </svg>
        </div>
    </div>
    <p class="mt-8 text-gray-500 text-sm">No more indecision. Start your journey now.</p>
</div>
