<?php

// Generated by Copilot

namespace App\Livewire;

use Livewire\Component;
use Livewire\Attributes\Layout;

/**
 * Landing page component that introduces the application and provides entry points
 * for creating decision lists and exploring features.
 */
#[Layout('layouts.app')]
class LandingPage extends Component
{
    /**
     * Start creating a new list immediately
     */
    public function createList()
    {
        return redirect()->route('lists.create');
    }

    /**
     * View example lists to understand how the app works
     */
    public function viewExamples()
    {
        return redirect()->route('lists.examples');
    }

    /**
     * Render the landing page view
     */
    public function render()
    {
        return view('livewire.landing-page');
    }
}
