<?php

// Generated by Copilot

namespace App\Livewire;

use Livewire\Component;

class LandingPage extends Component
{
    public function getStarted()
    {
        // Redirect to registration or onboarding
        return redirect()->route('register');
    }
}
